name: agoradesk
description: Person-to-person platform to allow anyone to trade their local currency for cryptocurrency.

publish_to: 'none'

version: 0.0.0+22

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^4.2.0
  auto_size_text: ^3.0.0
  connectivity_plus: ^2.3.0
  flutter_verification_code: ^1.1.2+1
  device_info_plus: ^4.1.2
  package_info_plus: ^1.4.3+1
  dio: ^4.0.6
  event_bus: ^2.0.0
  flutter_keyboard_visibility: ^5.2.0
  flutter_screenutil: ^5.0.2
  in_app_review: ^2.0.4
  url_launcher: ^6.0.17
  intl: ^0.17.0-nullsafety.2
  rxdart: ^0.27.3
  timeago: ^3.2.2
  provider: ^6.0.1
  sentry_flutter: ^6.2.2
  collection: ^1.15.0
  rating_dialog: ^2.0.3
  visibility_detector: ^0.3.3
  permission_handler: ^8.3.0
  cached_network_image: ^3.2.0
  json_annotation: ^4.4.0
  share_plus: ^4.0.4
  new_version: ^0.2.3
  objectbox: ^1.5.0
  objectbox_flutter_libs: ^1.4.1
  overlay_support: ^2.0.1
  plausible_analytics: ^0.1.3
  figma_squircle: ^0.5.3
  freezed_annotation: any
  easy_debounce: ^2.0.2
  extended_image: ^6.0.1
  pretty_dio_logger: ^1.1.1
  path_provider: ^2.0.8
  flutter_pin_code_widget: 0.0.4+2
  flutter_secure_storage: ^5.0.2
  dots_indicator: ^2.0.0
  currency_picker: ^2.0.7
  country_picker: ^2.0.11
  dropdown_search: ^5.0.2
  markdown_widget: ^1.2.7
  expandable: ^5.0.1
  #  flutter_mapbox_autocomplete: ^2.0.0
  mapbox_search: ^3.0.1+2
  #  readmore: ^2.1.0
  flutter_svg: ^1.1.0
  uni_links: ^0.5.1
  mobile_scanner: ^1.1.1
  qr_flutter: ^4.0.0
  shimmer: ^2.0.0
  image_picker: ^0.8.5+3
  percent_indicator: ^4.2.1
  unifiedpush: ^4.0.0
  insta_image_viewer: ^0.0.1+3
  firebase_core: ^1.20.0
  firebase_messaging: ^12.0.1
  get_it: ^7.2.0
  awesome_notifications: ^0.6.17
  flutter_foreground_task: ^3.7.3
  google_api_availability: ^3.0.1
  duration: ^3.0.11
  decimal: ^2.2.0
  webview_flutter: ^3.0.4
  sticky_headers: ^0.3.0+2

#dependency_overrides:
#  flutter_verification_code:
#    path: ../flutter_verification_code

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^1.0.0
  auto_route_generator: any
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2
  json_serializable: ^6.1.3
  objectbox_generator: ^1.4.1
  freezed: ^1.1.0
  mocktail: ^0.3.0


flutter:

  uses-material-design: true

  assets:
    - assets/banks/
    - assets/json/
    - assets/branding/
    - assets/images/

  fonts:
    - family: agoraFont
      fonts:
        - asset: assets/fonts/agoraFont.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400

flutter_intl:
  enabled: true
