name: agoradesk
description: Person-to-person platform to allow anyone to trade their local currency for cryptocurrency.

publish_to: 'none'

version: 1.0.70+93

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^5.0.1
  vm: ^1.0.4
  auto_size_text: ^3.0.0
  connectivity_plus: ^3.0.3
  flutter_verification_code: ^1.1.2+1
  device_info_plus: ^8.0.0
  package_info_plus: ^3.0.2
  dio: ^4.0.6
  dio_logging_interceptor: ^1.0.1
  event_bus: ^2.0.0
  flutter_keyboard_visibility: ^5.2.0
  flutter_screenutil: ^5.0.2
  url_launcher: ^6.0.17
  intl: ^0.17.0
  rxdart: ^0.27.7
  timeago: ^3.2.2
  provider: ^6.0.5
  sentry_flutter: ^6.20.1
  collection: ^1.15.0
  rating_dialog: ^2.0.3
  visibility_detector: ^0.3.3
  cached_network_image: ^3.2.0
  json_annotation: ^4.4.0
  share_plus: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.15
  overlay_support: ^2.0.1
  plausible_analytics: ^0.2.1
  figma_squircle: ^0.5.3
  freezed_annotation: any
  easy_debounce: ^2.0.2
  extended_image: ^7.0.0
  path_provider: ^2.0.8
  flutter_pin_code_widget: ^0.1.0
  flutter_secure_storage: ^8.0.0
  dots_indicator: ^2.0.0
  currency_picker: ^2.0.7
  country_picker: ^2.0.11
  dropdown_search: ^5.0.6
  markdown_widget: ^1.2.9
  expandable: ^5.0.1
  flutter_svg: ^2.0.4
  uni_links: ^0.5.1
  barcode_scan2: ^4.2.4
  qr_flutter: ^4.0.0
  shimmer: ^2.0.0
  image_picker: ^0.8.5+3
  percent_indicator: ^4.2.1
  insta_image_viewer: ^1.0.2
  firebase_core: ^2.8.0
  firebase_messaging: ^14.3.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  flutter_local_notifications: ^13.0.0
  flutter_foreground_task: ^3.8.2
  google_api_availability: ^3.0.1
  duration: ^3.0.11
  decimal: ^2.2.0
  sticky_headers: ^0.3.0+2
  flutter_displaymode: ^0.5.0
  flutter_inappwebview: ^5.7.2+3
  permission_handler: ^10.0.0
  restart_app: ^1.1.0
  local_auth: ^2.1.2
  flutter_keyboard_size: ^1.0.1
  store_checker: ^1.1.0
  just_the_tooltip: ^0.0.12
  flutter_app_badger: ^1.5.0
  expansion_tile_card: ^2.0.0

dependency_overrides:
  #  flutter_foreground_task:
  #    path: ../flutter_foreground_task
  flutter_foreground_task:
    git:
      url: https://github.com/sergdeus/flutter_foreground_task
      ref: master
#  flutter_pin_code_widget:
#    path: ../flutter_pin_code_widget

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^2.0.1
  auto_route_generator: any
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  hive_generator: any
  freezed: ^2.1.0
  mocktail: any
  injectable_generator: any


flutter:

  uses-material-design: true

  assets:
    - assets/banks/
    - assets/json/
    - assets/branding/
    - assets/images/
    - assets/misc/

  fonts:
    - family: agoraFont
      fonts:
        - asset: assets/fonts/agoraFont.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400

flutter_intl:
  enabled: true
