name: AgoraCI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta' # 'dev', 'alpha', default to: 'stable'

      - uses: actions/checkout@v3

      - name: Download dependencies
        run: flutter pub get

#      - name: Run Flutter Analyzer
#        run: flutter analyze

      - name: Run unit tests
        run: flutter test
