#  https://stefma.medium.com/how-to-store-a-android-keystore-safely-on-github-actions-f0cef9413784
#  KEY_PROPERTIES - file
#  RELEASE_AGORADESK_KEYSTORE
#  RELEASE_AGORADESK_KEYSTORE_SECRET
#  RELEASE_LOCALMONERO_KEYSTORE
#  RELEASE_LOCALMONERO_KEYSTORE_SECRET
#  AGORADESK_GOOGLE_SERVICES_JSON
#  LOCALMONERO_GOOGLE_SERVICES_JSON
#  MAPBOX_KEY
#  FIREBASE_OPTIONS_AGORADESK
#  FIREBASE_OPTIONS_LOCALMONERO

name: BuildFromTagsCI

on:
  push:
#    tags:
#      - "v*.*.*"
jobs:
  build:
    name: Build APK & AppBundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Decrypt secret
        env:
          RELEASE_AGORADESK_KEYSTORE_SECRET: ${{ secrets.RELEASE_AGORADESK_KEYSTORE_SECRET }}
          RELEASE_AGORADESK_KEYSTORE: ${{ secrets.RELEASE_AGORADESK_KEYSTORE }}
        run: ./decrypt_secret.sh > ./android/app/agoradesk-keystore.jks

      - name: Save Firebase options files
        env:
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
          AGORADESK_GOOGLE_SERVICES_JSON: ${{ secrets.AGORADESK_GOOGLE_SERVICES_JSON }}
          LOCALMONERO_GOOGLE_SERVICES_JSON: ${{ secrets.LOCALMONERO_GOOGLE_SERVICES_JSON }}
          FIREBASE_OPTIONS_AGORADESK: ${{ secrets.FIREBASE_OPTIONS_AGORADESK }}
          FIREBASE_OPTIONS_LOCALMONERO: ${{ secrets.FIREBASE_OPTIONS_LOCALMONERO }}
          MAPBOX_KEY: ${{ secrets.MAPBOX_KEY }}
        run: |
          printf "$KEY_PROPERTIES" > ./android/key.properties
          printf "$AGORADESK_GOOGLE_SERVICES_JSON" > ./android/app/src/agoradesk/google-services.json
          printf "$LOCALMONERO_GOOGLE_SERVICES_JSON" > ./android/app/src/localmonero/google-services.json
          printf "$FIREBASE_OPTIONS_AGORADESK" >> ./lib/firebase_options_agoradesk.dart
          printf "$FIREBASE_OPTIONS_LOCALMONERO" > ./lib/firebase_options_localmonero.dart
          mkdir ./lib/keys
          printf "const keysMapToken = '$MAPBOX_KEY';" > ./lib/keys/keys.dart

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Run read-yaml action
        id: yaml-data
        uses: KJ002/read-yaml@main
        with:
          file: './pubspec.yaml'
          key-path: '["version"]' # Access the runs key then the using key and retuns the value.

      - name: Display read-yaml output
        env:
          APP_VERSION: ${{ steps.yaml-data.outputs.data }}
        run: |
          echo "$APP_VERSION"
          appBuildNumber=${{ APP_VERSION#*+ }}
          echo "${{ steps.appBuildNumber }}"

#      - uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'
#
#      - run: flutter pub get
#
#      - name: Build-runner
#        run: flutter packages pub run build_runner build --delete-conflicting-outputs

#      - name: Build AgoraDesk APK (Refular + FOSS)
#        run: |
#          flutter build apk --flavor agoradesk --dart-define=app.flavor=agoradesk
#          mv build/app/outputs/flutter-apk/app-agoradesk-release.apk build/app/outputs/flutter-apk/com.agoradesk.app_${{ appBuildNumber }}.apk
#          flutter build apk --flavor agoradesk --dart-define=app.flavor=agoradesk --dart-define=app.includeFcm=false
#          mv build/app/outputs/flutter-apk/app-agoradesk-release.apk build/app/outputs/flutter-apk/com.agoradesk.app-foss_$appBuildNumber.apk

#      - name: Create Github Release
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/flutter-apk/*.apk"
#          bodyFile: "RELEASE.md"
#          token: ${{ secrets.RELEASES_TOKEN }}